jsonnet: Add External mixin support
prometheus-operator/kube-prometheus pull request #1054
Opened 2021-03-22 23:56 UTC by adinhodovic

Not sure if this is the correct approach but it's a feature I need since the 0.7 upgrade. 

Maybe it should not be a component but did not know where it should fit otherwise.

Usage:

```jsonnet
      externalMixins+: {
        mixins: [
          {
            name: 'sample', // Alerting rule name and dashboard Configmap name
            namespace: 'abc', // Can be omitted
            dashboardFolder: ''Misc", // Can be omitted
            mixin: import 'blackbox-exporter-mixin/mixin.libsonnet', // Add your custom configuration when importing the mixin
          },
        ],
      },
```

Would add documentation if the approach is fine. Pointers/hints are appreciated :)

2021-03-23 07:42 UTC, paulfantom requested changes
Overall, this is a nice piece of code, but I don't see this as part of `components/` as there is no particular component this adds. This looks like something that is meant to be living downstream or sth that could be simplified and included as an `addon`.

Inclusion of mixins was meant as something user does in their own implementation. For example: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/jsonnet/main.jsonnet#L427-L436 and not something we provide additional wrapper framework.

2021-03-23 07:42 UTC, paulfantom commented on jsonnet/kube-prometheus/components/external-mixins.libsonnet
> +};
What is the value of adding default values when there is no default component? This way we have mostly incorrect labels and in current form, this doesn't provide any guidance as to what is configurable.

2021-03-23 07:42 UTC, paulfantom commented on jsonnet/kube-prometheus/components/external-mixins.libsonnet
> +  },
Why complicate it more than it is in https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/prometheus-additional-alert-rule-example.jsonnet ?

2021-03-23 11:05 UTC, adinhodovic commented
> Overall, this is a nice piece of code, but I don't see this as part of `components/` as there is no particular component this adds. This looks like something that is meant to be living downstream or sth that could be simplified and included as an `addon`.
> 
> Inclusion of mixins was meant as something user does in their own implementation. For example: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/jsonnet/main.jsonnet#L427-L436 and not something we provide additional wrapper framework.
The details regarding the implementation make sense. Overall, do you see a place for it as a addon or should it be downstream? I have the same approach as in the ankhmorpork repository, however just found it simpler and more automate-friendly previously with the top level variables for alerts, dashboards and rules (just importing the mixin was sufficient for me). I understood the reasoning behind the change but it left external mixin support requiring more code downstream but maybe that is how it should be.

2021-03-23 11:49 UTC, paulfantom commented
> it left external mixin support requiring more code downstream but maybe that is how it should be.

IMHO that is how it should be. Importing mixins in one PrometheusRule can lead to similar issues we experienced in kube-prometheus and because of which we did a refactor. Mainly this will make all `_config` fields from various mixins a global field in the mixins context. This means if 2 mixins use the same name field in `_config` for different purposes, users will end up with issues that won't manifest themselves immediately.

---

I imagine we could create an example of how to integrate a mixin with kube-prometheus. What if we could create a function that accepts an imported and configured mixin as a parameter and outputs `PrometheusRule` and hidden `grafanaDashboard` objects? This way we could use that function many times with many mixins and output rules in multiple objects avoiding global variable problems.

Sth like:
```
# Function adding mixin
local addMixin(mixin) = {
  # function content
}

# Mixin A configuration and import
local mixinConfA = (import 'somemixin') + {
  _config+:: {
    someconfiguration
  }
}

local mixinA = addMixin(mixinConfA);

# Inline import and configuration of mixin B
local mixinB = addMixin((import 'someothermixin') + {
  _config+:: {
    someotherconfiguration
  }
});

# kube-prometheus initialization
local kp = (import 'kube-prometheus/main.libsonnet') + {
 values+:: {
   grafana+: {
     dashboards+: mixinA.grafanaDashboard + mixinB.grafanaDashboard,
   }
 }
}

# Manifestation
...
{ ['otherMixins/mixinA-PrometheusRule']: mixinA.PrometheusRule } + 
{ ['otherMixins/mixinB-PrometheusRule']: mixinB.PrometheusRule } + 
```

I know this isn't as convenient as it was before refactored. However, that convenience had a high price which wasn't justified.

2021-03-23 12:29 UTC, paulfantom commented
We could potentially also create some `lib/` directory for this sort of functions instead of having everything in `examples/`. This should simplify using them downstream.

2021-03-23 13:21 UTC, adinhodovic commented
> We could potentially also create some `lib/` directory for this sort of functions instead of having everything in `examples/`. This should simplify using them downstream.

I would not mind a lib directory with functions. Don't mind drafting a WIP for this, however not sure if it's causing too much hassle for the project. Examples are fine, but are not really extensible, it creates a copy/paste workflow similar to Yaml (in this case I'd also prefer my downstream jsonnet files to be very similar to the upstream examples to the point where these examples could just be functions). If I can use the jb bundler to use functions in a manner of here's my mixin and give me rules/dashboards with this config as you stated. Even though mixins are not core components of kube-prometheus, I still see them as great benefits to overall usage of Jsonnet especially if adoption grows of mixins, but the DX is not great for tweaking kube-prometheus without having deep knowledge of the project as you guys do.

IMHO, not sure if I'd like to introduce a lib directory just for this usecase if it's not part of a path other parts would move towards and utilize.

2021-03-23 16:18 UTC, paulfantom commented
> IMHO, not sure if I'd like to introduce a lib directory just for this usecase if it's not part of a path where other pieces would move towards and utilize.

I have a bit more function ideas that could be put into such a directory, so don't worry about starting WIP with `lib/` dir :)

2021-03-28 12:31 UTC, adinhodovic commented
Updated to a function, example usage would be:

```jsonnet
local addMixin = (import 'kube-prometheus/lib/mixin.libsonnet');

local jaegerMixin = addMixin({
  name: 'jaeger',
  namespace: 'observability', // optional
  dashboardFolder: 'Observability', // optional
  mixin: import 'jsonnet-libs/jaeger-mixin/mixin.libsonnet',
});
```

With custom _config overwriting:

```jsonnet
local jaegerMixin = addMixin({
  name: 'jaeger',
  namespace: 'observability',  // optional
  dashboardFolder: 'Observability',  // optional
  mixin: (import 'jsonnet-libs/jaeger-mixin/mixin.libsonnet') + {
    _config+:: {
      jaegerSelector: 'my-selector',
    },
  },
});
```

Then you'll create rules/alerts with:

```jsonnet
{ 'external-mixins/jaeger-prometheus-rules': jaeger.prometheusRules } +
{ 'external-mixins/jaeger-prometheus-alerts': jaeger.prometheusAlerts }
```

And you'll import dashboards by:

```jsonnet
grafana+: {
  dashboards+: jaegerMixin.grafanaDashboards,
}
```
If you pass dashboardFolder then you'll pass the grafanaDashboards to the folderDashboards param instead:

```jsonnet
grafana+: {
  folderDashboards+:: {
     Kubernetes: {
        ...
     },
     Misc: {
       'grafana-home.json': import 'dashboards/misc/grafana-home.json',
      },
} + jaegerMixin.grafanaDashboards,
```

2021-04-06 07:47 UTC, paulfantom commented on jsonnet/kube-prometheus/lib/mixin.libsonnet
> +  },
Why not wrap it into one object?

2021-04-06 07:48 UTC, paulfantom reviewed
lgtm, just one nit

2021-04-06 10:04 UTC, adinhodovic commented on jsonnet/kube-prometheus/lib/mixin.libsonnet
> +  },
Fine either way :) Fixed

2021-04-08 07:11 UTC, merged

2021-04-08 07:11 UTC, paulfantom commented
Thank you! :+1:

2021-04-08 12:19 UTC, sdurrheimer commented
> ```jsonnet
> { 'external-mixins/jaeger-prometheus-rules': jaeger.prometheusRules } +
> { 'external-mixins/jaeger-prometheus-alerts': jaeger.prometheusAlerts }
> ```

Where would you put those in the main kube-prometheus jsonnet file?

2021-04-08 13:03 UTC, adinhodovic commented
> > ```jsonnet
> > { 'external-mixins/jaeger-prometheus-rules': jaeger.prometheusRules } +
> > { 'external-mixins/jaeger-prometheus-alerts': jaeger.prometheusAlerts }
> > ```
> 
> Where would you put those in the main kube-prometheus jsonnet file?
> 
> Would be nice to have proper usage documentation for that lib.

It is not tied to the **main** kube-prometheus jsonnet file. This just creates jsonnet objects that you can put anywhere, e.g top level of any jsonnet file. Example:

```jsonnet
// serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
{ 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
...
{ 'external-mixins/my-mixin-rules': myMixin.prometheusRules } // ur RULES
```

The dashboards are tied to the main kube-prometheus jsonnet file(needs to be passed as values to the grafanaDashboards variable) as you can see in the previous example. I don't mind opening PR for a doc page for the lib if @paulfantom gives a hint under which dir/MD file it should be added.

2021-04-08 13:24 UTC, sdurrheimer commented
Ok so a complete example would look like this:
```jsonnet
local addMixin = (import 'kube-prometheus/lib/mixin.libsonnet');

local yourMixin = addMixin({
  name: 'your',
  mixin: import 'your-mixin/mixin.libsonnet',
});

local anotherMixin = addMixin({
  name: 'another',
  namespace: 'monitoring', // optional
  dashboardFolder: 'Observability', // optional
  mixin: (import 'another-mixin/mixin.libsonnet') + {
    // with custom _config overwriting
    _config+:: {
      selector: 'my-selector',
    },
  },
});

local kp =
  (import 'kube-prometheus/main.libsonnet') +
  // Uncomment the following imports to enable its patches
  // (import 'kube-prometheus/addons/anti-affinity.libsonnet') +
  // (import 'kube-prometheus/addons/managed-cluster.libsonnet') +
  // (import 'kube-prometheus/addons/node-ports.libsonnet') +
  // (import 'kube-prometheus/addons/static-etcd.libsonnet') +
  // (import 'kube-prometheus/addons/custom-metrics.libsonnet') +
  // (import 'kube-prometheus/addons/external-metrics.libsonnet') +
  {
    values+:: {
      common+: {
        namespace: 'monitoring',
      },
      grafana+: {
        dashboards+: yourMixin.grafanaDashboards +
        {
          // custom dashboards
        },

        // when using dashboardFolder
        folderDashboards+:: anotherMixin.grafanaDashboards +
        {
          // custom folder dashboards
        },
      },
    },
    prometheusRules+:: {
      'your-mixin': yourMixin.prometheusRules,
      'another-mixin': anotherMixin.prometheusRules,
    },
  };

{ 'setup/0namespace-namespace': kp.kubePrometheus.namespace } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor' && name != 'prometheusRule'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
{ 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['kubernetes-' + name]: kp.kubernetesControlPlane[name] for name in std.objectFields(kp.kubernetesControlPlane) }
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ [name + '-prometheusRule']: kp.prometheusRules[name], for name in std.objectFields(kp.prometheusRules) }
```

Right?

2021-04-08 13:36 UTC, adinhodovic commented
> Ok so a complete example would look like this:
> 
> 
> Right?

No the `prometheusRules` is not used since 0.7 and this library is not tied to that variable. Your example would be:

 ```jsonnet
 local addMixin = (import 'kube-prometheus/lib/mixin.libsonnet');
 
 local yourMixin = addMixin({
   name: 'your',
   mixin: import 'your-mixin/mixin.libsonnet',
 });
 
 local anotherMixin = addMixin({
   name: 'another',
   namespace: 'monitoring', // optional
   dashboardFolder: 'Observability', // optional
   mixin: (import 'another-mixin/mixin.libsonnet') + {
     // with custom _config overwriting
     _config+:: {
       selector: 'my-selector',
     },
   },
 });
 
 local kp =
   (import 'kube-prometheus/main.libsonnet') +
   // Uncomment the following imports to enable its patches
   // (import 'kube-prometheus/addons/anti-affinity.libsonnet') +
   // (import 'kube-prometheus/addons/managed-cluster.libsonnet') +
   // (import 'kube-prometheus/addons/node-ports.libsonnet') +
   // (import 'kube-prometheus/addons/static-etcd.libsonnet') +
   // (import 'kube-prometheus/addons/custom-metrics.libsonnet') +
   // (import 'kube-prometheus/addons/external-metrics.libsonnet') +
   {
     values+:: {
       common+: {
         namespace: 'monitoring',
       },
       grafana+: {
         dashboards+: yourMixin.grafanaDashboards +
         {
           // custom dashboards
         },
 
         // when using dashboardFolder
         folderDashboards+:: anotherMixin.grafanaDashboards +
         {
           // custom folder dashboards
         },
       },
     },
   };
 
 { 'setup/0namespace-namespace': kp.kubePrometheus.namespace } +
 {
   ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
   for name in std.filter((function(name) name != 'serviceMonitor' && name != 'prometheusRule'), std.objectFields(kp.prometheusOperator))
 } +
 // serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready
 { 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
 { 'prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule } +
 { 'kube-prometheus-prometheusRule': kp.kubePrometheus.prometheusRule } +
 { ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
 { ['blackbox-exporter-' + name]: kp.blackboxExporter[name] for name in std.objectFields(kp.blackboxExporter) } +
 { ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
 { ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
 { ['kubernetes-' + name]: kp.kubernetesControlPlane[name] for name in std.objectFields(kp.kubernetesControlPlane) }
 { ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
 { ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
 { ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
 { [name + '-prometheusRule']: kp.prometheusRules[name], for name in std.objectFields(kp.prometheusRules) } +
 // HERE
 { 'your-mixin': yourMixin.prometheusRules } +
 { 'another-mixin': anotherMixin.prometheusRules }
 ```


```

2021-04-08 13:46 UTC, sdurrheimer commented
Yes I know the `prometheusRules` not used anymore, but I feel it would make it more dynamic by avoiding repeating multiple `{ 'your-mixin': yourMixin.prometheusRules } +` add the end of your main jsonnet file.

Similar to the [ingress](https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/ingress.jsonnet#L118) example and easier to maintain:
You have a new mixin to add? Declare the mixin and add it to the `prometheusRules` map, done.

2021-04-08 14:49 UTC, paulfantom commented
> You have a new mixin to add? Declare the mixin and add it to the prometheusRules map, done.

This is exactly what we **don't** want to do nor to advertise as it makes all mixins global and can cause potential problems which are hard to debug. The recommendation is to create at least one PrometheusRule object per mixin.

2021-04-08 15:03 UTC, sdurrheimer commented
> > You have a new mixin to add? Declare the mixin and add it to the prometheusRules map, done.
> 
> This is exactly what we **don't** want to do nor to advertise as it makes all mixins global and can cause potential problems which are hard to debug. The recommendation is to create at least one PrometheusRule object per mixin.

`{ [name + '-prometheusRule']: kp.prometheusRules[name], for name in std.objectFields(kp.prometheusRules) } +` is a loop, it will create one `PrometheusRule` object per mixin.

2021-04-08 15:56 UTC, adinhodovic commented
> > > You have a new mixin to add? Declare the mixin and add it to the prometheusRules map, done.
> > 
> > 
> > This is exactly what we **don't** want to do nor to advertise as it makes all mixins global and can cause potential problems which are hard to debug. The recommendation is to create at least one PrometheusRule object per mixin.
> 
> `{ [name + '-prometheusRule']: kp.prometheusRules[name], for name in std.objectFields(kp.prometheusRules) } +` is a loop, it will create one `PrometheusRule` object per mixin `prometheusRules` map entry.

If it's one object they will share top level _config, mixins have various configuration settings and some might overwrite each other. This lib is fine and the discussion isn't around the library/pr, feel free to open a new one if you know a better way to use the generated rules from the lib. However, I agree that documentation is needed and I'll open a PR soon.