.github/workflows: automatically update jsonnet dependencies
prometheus-operator/kube-prometheus pull request #1220
Opened 2021-06-22 14:55 UTC by fpetkovski

This commit extends the `versions` github workflow to automatically update
jsonnet dependencies when the jsonnet code in upstream repositories changes.

2021-06-23 14:01 UTC, ArthurSens reviewed
I really like the idea of automating the dependency updates 🙂, that's one of the most frequent PRs we have. I'm not sure if we want it in the same job as the "components update" or in a separate CI job.

@paulfantom @dgrisonnet what do you think?

2021-06-23 14:08 UTC, paulfantom commented
I don't think it is necessary to have it in a separate job. Although I am thinking about reducing the frequency of this cronjob, I think it might be enough to update deps/versions once a week and not daily. WDYT?

2021-06-23 14:36 UTC, fpetkovski commented
One concern I have with running the job weekly is that this might defeat its purpose. The idea behind the automation is to check for updates regularly so that it makes the PR before someone needs it.

2021-06-23 17:49 UTC, paulfantom commented
> The idea behind the automation is to check for updates regularly so that it makes the PR before someone needs it.

The main idea behind any automation is to reduce the mental toil of maintaining the software. With the current model of daily updates, it seems to actually increase the toil and not reduce it as we have quite frequent version updates and new PRs ([7 PRs in 15 days](https://github.com/prometheus-operator/kube-prometheus/pulls?q=is%3Apr+sort%3Aupdated-desc+%5Bbot%5D)).

Considering that upstream projects tend to be slow-moving in regards to jsonnet code and the only part that is faster-paced are mixins, I don't see anything wrong with doing automated updates once a week. We still have the option to manually update dependency if someone needs it sooner. IMHO this will give a feeling of being in control of the code that is written while still allowing kube-prometheus project not to stay far from the dependencies HEAD.

2021-06-23 17:51 UTC, paulfantom requested changes
PR title and body message in "Create Pull Request" job need to be adjusted to reflect this is potentially not only changing version but also jsonnet code.

2021-06-23 19:28 UTC, dgrisonnet commented
I completely agree with Pawel here, putting everything under the "Create Pull Request" job and reducing the frequency to every week seems like the solution that would put a fewer toll on the maintainers. That said, I have a personal preference for every Monday so that we can start the week with an up-to-date version of kube-prometheus, pulling every changes from the week prior.

2021-06-25 09:32 UTC, dgrisonnet approved these changes
lgtm

2021-06-25 09:33 UTC, fpetkovski commented
Related PR for adjusting the schedule: https://github.com/prometheus-operator/kube-prometheus/pull/1227

2021-06-25 11:23 UTC, merged