Remove hostPort from node-export daemonset
prometheus-operator/kube-prometheus pull request #1612
Opened 2022-02-02 13:29 UTC by ArthurSens

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

HostPort can cause different scheduling problems as documented here: https://hub.armo.cloud/docs/c-0044

The node-exporter pod doesn't have any requirements to have that enabled, so let's just get rid of it (for some reason it is kube-rbac-proxy that has the HostPort set as a workaround)

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
Remove hostPort from node-exporter daemonset
```

2022-02-02 16:59 UTC, paulfantom commented
I just tested running this and surprisingly `hostPort` was still added. Seems like DaemonSet controller is adding `hostPort` when `hostNetwork` is `true`. 

I am looking for kubernetes code references as to why this is the case.

2022-02-02 17:10 UTC, paulfantom requested changes
Seems like it will always run with `hostPort` due to `hostNetwork: true`.

From k8s API docs about `hostPort`:
> Number of port to expose on the host. If specified, this must be a valid port number, 0 < x < 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this.

Seems like Kubernetes will always set hostPort because of:
- https://github.com/kubernetes/kubernetes/blob/1945829906546caf867992669a0bfa588edf8be6/pkg/apis/core/v1/defaults.go#L195-L198
- https://github.com/kubernetes/kubernetes/blob/1945829906546caf867992669a0bfa588edf8be6/pkg/apis/core/v1/defaults.go#L402-L411

As such I think it might be better to leave `hostPort` the way it was and document this caveat better.

2022-02-02 22:58 UTC, ArthurSens commented
Ah damn, thanks for taking a deeper look into this!

I just added a link for k8s codebase trying to explain why we keep it

2022-02-03 13:04 UTC, paulfantom commented
Could you also add this information to https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/security.md ?

2022-02-03 15:44 UTC, ArthurSens commented
> Could you also add this information to https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/security.md ?

Ah yes, good catch

2022-02-04 07:28 UTC, ArthurSens commented
Well that's akward, not sure why all of a sudden Kubescape is saying that we're running Prometheus Adapter with the root user 🤔

2022-02-04 11:58 UTC, paulfantom approved these changes

2022-02-04 11:58 UTC, merged