etcd: Add Prometheus alerting and recording rules
prometheus-operator/kube-prometheus pull request #1769
Opened 2022-05-25 23:22 UTC by centromere

## Description

The official etcd project provides a [mixin](https://github.com/etcd-io/etcd/tree/main/contrib/mixin) for Prometheus rules and Grafana dashboards. They do not publish auto-generated YAML, so the kube-prometheus-stack project is currently [syncing](https://github.com/prometheus-community/helm-charts/blob/2e86d1618eb5d599576789c1202853dc5bc808c0/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L63) against an old ruleset. This ruleset is from the etcd 3.4 documentation, but modern versions of Kubernetes use etcd 3.5+.

## Type of change

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

```release-note
etcd: Add Prometheus alerting and recording rules
```

2022-05-26 22:21 UTC, ArthurSens commented
Thanks for raising the pull request 🙂

Although I agree that alerting on etcd failures makes sense with this project, the mixin provided by the etcd project is not very compatible with several kubernetes providers 😬.

I just tested deploying the changes from this PR to minikube, kind and gke. All of them don't have the metrics required by the alerts of etcd's mixin

2022-05-27 03:11 UTC, centromere commented
If I recall correctly, the metrics come directly from etcd, not the apiserver.

2022-05-27 08:17 UTC, paulfantom requested changes
I don't think this should be enabled by default. IMHO there is no point in adding rules when we don't add a ServiceMonitor for etcd. As such I think this should be part of [`static-etcd.libsonnet`](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/static-etcd.libsonnet) addon.

2022-08-08 16:35 UTC, centromere commented
WIth https://github.com/prometheus-community/helm-charts/pull/2340 having been merged, this PR is no longer relevant.

2022-08-08 16:35 UTC, closed without merging