added release 0.12 and k8s 1.25 and 1.26 to table
prometheus-operator/kube-prometheus pull request #2005
Opened 2023-02-05 12:35 UTC by KlavsKlavsen

add release 0.12 and k8s 1.25 and 1.26 to table in readme

2023-02-13 16:33 UTC, simonpasquier commented
:wave: thanks for the PR! The doc linter isn't happy apparently.

2023-02-14 10:30 UTC, PhilipGough commented
I think this one should be closed in favour of the pre-existing #2000

2023-02-14 10:48 UTC, PhilipGough commented
@KlavsKlavsen sorry, I did not look closely enough, we can add this, but we should remove the oldest version from the matrix too so feel free to do so

2023-02-24 12:03 UTC, KlavsKlavsen commented
Lint fixes, per codium lint comments - and removed k8s 1.20 from list.

2023-02-24 12:35 UTC, KlavsKlavsen commented
Appearently that did not make your linter happy..  :(
I simply cannot see the difference in the "formatted" vs. original line it is complaining about - its really unhelpful output.
Any tips on what it could be - that codium standard markdown linter doesn't complain about?

2023-05-11 17:40 UTC, sylvainfaivre commented
Hi, updating the compatibility matrix would be good, as k8s 1.26 and 1.27 have been released. The thing is, the CI logs for this PR have expired, so how could it be merged ?

2023-05-18 08:54 UTC, mkiejda requested changes

2023-05-18 08:54 UTC, mkiejda commented on README.md
> +| [`release-0.12`](https://github.com/prometheus-operator/kube-prometheus/tree/release-0.11) | ✗               | ✗               | ✗               | ✔               | ✔               | ✔
```suggestion
| [`release-0.12`](https://github.com/prometheus-operator/kube-prometheus/tree/release-0.12) | ✗               | ✗               | ✗               | ✔               | ✔               | ✔               |
```

2023-05-24 14:54 UTC, philipgough commented
Closing in favour of #2121

2023-05-24 14:54 UTC, closed without merging