Test against 1.18 and 1.19
prometheus-operator/kube-prometheus pull request #669
Opened 2020-09-09 16:14 UTC by lilic

We should be testing against 1.18 and 1.19, with 1.18 being dropped for testing in master. 
cc @prometheus-operator/kube-prometheus-reviewers

2020-09-10 08:17 UTC, paulfantom requested changes

2020-09-10 08:17 UTC, paulfantom commented on tests/e2e/travis-e2e.sh
> +    run_e2e_tests $cluster_version
This split should be done in travis to allow testing in parallel and speed things up. Doing this in bash will cloud things and make CI 2x slower to return results.

2020-09-10 08:18 UTC, paulfantom commented
Why this PR is towards `release-0.6` and not `master`?

2020-09-10 12:21 UTC, paulfantom commented on tests/e2e/travis-e2e.sh
> +    run_e2e_tests $cluster_version
SGTM

2020-09-10 12:27 UTC, paulfantom commented
> PR against master was already merged

Master is not tested against multiple k8s version, only against 1.19. Hence [my comment about the parallelization of tests](https://github.com/prometheus-operator/kube-prometheus/pull/669#discussion_r486152539).

Additionally, if we want to test `release-0.6` against 1.19 too, then the compatibility matrix should be amended: https://github.com/prometheus-operator/kube-prometheus#kubernetes-compatibility-matrix

2020-09-10 12:33 UTC, paulfantom commented
Instead of complicating bash script, we can expose one config parameter (k8s version) and paralelize in travis. Example is in https://github.com/prometheus-operator/kube-prometheus/pull/671

2020-09-10 12:53 UTC, lilic commented
> Master is not tested against multiple k8s version, only against 1.19. Hence my comment about the parallelization of tests.

Yes, well aware hence my comment :) 

> PR against master was already merged, we always test against latest k8s release in master and for releases whatever we support in the release branches

2020-09-22 08:03 UTC, paulfantom approved these changes
Let's merge it. This would be the last time we are using this mechanism :)

2020-09-22 08:10 UTC, s-urbaniak commented
lgtm then :+1:

2020-09-22 08:10 UTC, merged