Add SD devices to the list of node disks
prometheus-operator/kube-prometheus pull request #724
Opened 2020-10-13 04:40 UTC by jontg

I've found that my Raspberry Pi nodes aren't reporting storage metrics for their SD cards on the standard k8s dashboards, and it looks like this is why :-).

2020-10-16 08:04 UTC, brancz commented
Upstream is updated, so we can move ahead here :)

2020-10-21 04:01 UTC, jontg commented
@brancz feedback greatly appreciated — I know technically `jb update` works, but I'm following [this pattern](https://github.com/carlosedp/cluster-monitoring/blob/master/Makefile#L24-L25) which I've now seen in a few repos.  Thanks!

2020-10-30 09:41 UTC, metalmatze requested changes
This needs to be rebased and then lgtm :+1:

2020-10-30 09:41 UTC, metalmatze commented on Makefile
> +
I don't think we need this additional target. It's not use as dependency by another one and only adds one single command.

2021-02-25 18:10 UTC, paulfantom commented
After code refactoring and introducing `jsonnetfmt` as a CI job I don't think this is valid anymore. 

I am closing this, but please reopen if you think this is still needed.

2021-02-25 18:10 UTC, closed without merging