feat(Grafana-Dashboards): add cluster label to some metrics
prometheus-operator/kube-prometheus pull request #886
Opened 2021-01-22 11:36 UTC by secustor

Some queries in Grafana dashboards are missing the cluster labels. 

This PR tries to fix this.

2021-01-25 10:32 UTC, paulfantom requested changes
Those dashboards are coming from https://github.com/kubernetes-monitoring/kubernetes-mixin project and should be adjusted there. After this is completed we can update the project dependency.

2021-01-25 11:03 UTC, secustor commented
Here is the PR at the upstream project https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/542

2021-01-27 06:21 UTC, vsxen commented
I can not find any cluster label in those metrics, such as `container_memory_working_set_bytes `。why?

2021-01-27 09:47 UTC, secustor commented
I have the cluster label at these metrics: 
![image](https://user-images.githubusercontent.com/17493763/105973303-de86db80-608c-11eb-8d5f-093b340c8b48.png)

2021-01-27 12:03 UTC, vsxen commented
do you set external_labels in prom?

https://github.com/prometheus-operator/kube-prometheus/search?l=YAML&p=1&q=cluster

2021-10-05 12:26 UTC, paulfantom commented
This seems to be already completed. Please reopen if this is not already included.

2021-10-05 12:26 UTC, closed without merging